apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obi
  namespace: obi
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: "NoSchedule"
          key: "components.gke.io/gke-managed-components"
          operator: "Exists"
