apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - obi-configmap.yaml
  - obi-daemonset.yaml
  - demo-services.yaml
  - otel-collector.yaml
